[project]
name = "challenge-jusbrasil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = []
requires-python = ">=3.12,<3.13"
dependencies = [
    "bitsandbytes>=0.49.2",
    "gliner2>=1.0.0",
    "numpy>=2.2,<2.5",
    "pandas>=3.0.6",
    "vllm>=0.19.1",
    "vllm-bnb-plugin>=0.0.3",
]

[project.scripts]
challenge-jusbrasil = "challenge_jusbrasil.main:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
